services:

  poker_app:
    container_name: poker_app
    image: 'poker_app'
    build:
      dockerfile: Dockerfile
      context: .
    stdin_open: true
    env_file:
      - .env.production
    volumes:
      - ./:/app
    ports:
      - 8082:80
    # network_mode: host
